### ISSUE TITLE
Update Django to 3.0

### ISSUE THREAD

**Issue by afuetterer** [ddionrails/ddionrails#1003]
### Subject of the issue

Django 3.0 is out.
https://docs.djangoproject.com/en/3.0/releases/3.0/

Upgrading should be straightforward I guess?
https://docs.djangoproject.com/en/3.0/releases/3.0/#backwards-incompatible-3-0

**Comment by hansendx** [comment]
Thank you for opening the issue and for the information.

I've tried running the system with Django 3.0 but i had problems with two other requirements.
django-filer has required django version set to <3.0 and pip complained on installation.
django_elasticsearch_dsl did not specify specify Django <3.o in its requirements but crashed the whole system since it tried to use `django.utils.six` which was [removed](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis) in 3.0.

I'm going to keep checking back on django_elasticsearch_dsl in hopes that they update.

**Comment by afuetterer** [comment]
There are already two PRs for django-elasticsearch-dsl:
- https://github.com/sabricot/django-elasticsearch-dsl/pull/230
- https://github.com/sabricot/django-elasticsearch-dsl/pull/233

I guess it will be fixed soon.
