### ISSUE TITLE
Period of questionnaire not used for faceted search

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/ddionrails#426]
### Subject of the issue
If I search for "Q533" I get a result from questionnaire "soep-core-2017-pb-m34-wieder", this questionnaire has a period (2017), but this preiod is not used for the facetted search.

### Expected behaviour
At least "2017" should appear below "Period" in the left colum.

### Actual behaviour
Nothing appears below "Period" in the left colum.

### Steps to reproduce
Search for "Q533", get 2 questions, but no entry below Period.

**Comment by afuetterer** [comment]
The import of a question has to be changed to enable the "Expected behaviour".
The period information is saved with the instrument / questionnaire.
It can be accessed via `Question.instrument.period`.

The import of a question happens here:
https://github.com/ddionrails/ddionrails/blob/develop/instruments/imports.py#L42

@kwenzig Which attribute(s) of a period do you want to index in the search engine?

- [ ] period.name
- [ ] period.label
- [ ] period.description
- [ ] period.definition

**Comment by afuetterer** [comment]
see #597
