### ISSUE TITLE
Change returned Queryset of Question.get_concepts() method

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/ddionrails#427]
### Subject of the issue
https://paneldata.org/soep-core/inst/soep-core-2016-pe/4 is a single-item question with concept pgwert in questions.csv, but in paneldata.org there two additional concepts displayed.

### Expected behaviour
Display only the questions's concept (or concepts for multi-item questions).

**Comment by afuetterer** [comment]
If this is not desired, we need to change the method of a question to collect its "related" concepts. The question also collects "indirect_concepts" through related variables. This behaviour is "new" and part of @mhebing 's WP4.

@kwenzig : What is your opinion on this?

Source code responsible for the behaviour: Template, View, Model.

**Template:**
https://github.com/ddionrails/ddionrails/blob/develop/templates/questions/question_detail.html#L68

**View:**
https://github.com/ddionrails/ddionrails/blob/develop/instruments/views.py#L67

**Model:**
https://github.com/ddionrails/ddionrails/blob/develop/instruments/models.py#L165

**Comment by afuetterer** [comment]
Metadata responsible for the behaviour:

https://raw.githubusercontent.com/paneldata/soep-core/master/ddionrails/variables.csv
`soep-core,bgp,bgp04,plh0334,v33,,bgp|bgp04`
Variable bgp04 -> Concept plh0334

`soep-core,pl,plh0334,1633,,,pl|plh0334`
Variable plh0334-> Concept 1633

Maybe "going recursively" through generations.csv and logical_variables.csv created relations that you were not aware of?

Is it correct that Question "soep-core-2016-pe/4" is related to:
- `/soep-core/data/bgp/bgp04`
- `/soep-core/data/pl/plh0334`

Because they "bring the concepts".

**Comment by kwenzig** [comment]
The mentioned reasons (concepts from related questions) are plausible, but I would not expect the indirect_concepts to be displayed at this point.

**Comment by kwenzig** [comment]
Descision: These indirect_concepts should disappear.

**Comment by afuetterer** [comment]
Decisison is made and final?

Proposed change is to change the Question.get_concepts() method in 
https://github.com/ddionrails/ddionrails/blob/develop/instruments/models.py#L165

```python
    def get_concepts(self):
        concepts = Concept.objects.filter(
            concepts_questions__question_id=self.pk
        )
        return concepts.distinct()
```
or 

```python
    def get_concepts(self):
        concepts = Concept.objects.filter(
            concepts_questions__question_id=self.pk
        ).distinct()
        return concepts
```
or

```python
    def get_concepts(self):
        return Concept.objects.filter(
            concepts_questions__question_id=self.pk
        ).distinct()
```
This should suffice to achieve what @kwenzig 's expected behaviour describes.

@hansendx Which way of the method do you prefer? The return of the method is either a queryset of Concept objects or None. How to use type hints here?

see: https://stackoverflow.com/questions/42397502/how-to-use-python-type-hints-with-django-queryset

**Comment by afuetterer** [comment]
The method could also move to the Concept model as a custom queryset, as it effectively returns Concept objects.
