### ISSUE TITLE
Internal server error bei bfpage17/bfj9212

### ISSUE THREAD

**Issue by jhartma** [ddionrails/ddionrails#942]
### Subject of the issue
Internal server error

Describe your issue here.
https://paneldata.org/iab-soep-mig/data/bfpage17/bfj9212 zeigt Internal Server Error

### Expected behaviour
Beschreibung der Variable sollte angezeigt werden

Ist vielleicht im falschen Datensatz verortet? https://paneldata.org/soep-core/data/bfjugend/bfj921 funktioniert

**Comment by hansendx** [comment]
This stems from an error in the data, not the system.
I've fixed it on the production system and opened an issue at the data repository: https://github.com/paneldata/iab-soep/issues/19

**Comment by hansendx** [comment]
iab-soep-mig is a partial set of the soep-core data.
This is why the variable is at https://paneldata.org/iab-soep-mig/data/bfpage17/bfj9212
and at https://paneldata.org/soep-core/data/bfjugend/bfj9212 .

https://paneldata.org/soep-core/data/bfjugend/bfj9212 works because the data at https://github.com/paneldata/soep-core is not faulty in the way the data from https://github.com/paneldata/iab-soep is.
